In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

## Tensors basics

In [7]:
var = torch.tensor(7)
print(var)
print(var.ndim)
print(var.item())

tensor(7)
0
7


In [10]:
vec = torch.tensor([7, 7])
print(vec)
print(vec.ndim)
print(vec.shape)

tensor([7, 7])
1
torch.Size([2])


In [12]:
MATRIX = torch.tensor([[3,4.1], [9, -1]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 3.0000,  4.1000],
        [ 9.0000, -1.0000]])
2
torch.Size([2, 2])


In [16]:
print(MATRIX[0])
print(MATRIX[1][0])
print(MATRIX[:][0])

tensor([3.0000, 4.1000])
tensor(9.)
tensor([3.0000, 4.1000])
tensor([3.0000, 4.1000])


In [24]:
TENSOR = torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)

print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6]]])
3
torch.Size([1, 2, 3])


In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
TENSOR[0][0]

tensor([1, 2, 3])

In [25]:
random_tensor = torch.rand(3, 4)  # size = (3, 4) as params
print(random_tensor)

tensor([[9.8296e-01, 5.4342e-01, 6.5771e-01, 8.8094e-01],
        [9.5986e-01, 5.2897e-01, 4.0173e-01, 3.1790e-01],
        [4.3434e-04, 9.4538e-01, 4.2829e-01, 1.0020e-01]])


In [26]:
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)

tensor([[[0.4904, 0.0532, 0.5115, 0.3529],
         [0.2615, 0.4762, 0.4745, 0.2842],
         [0.4264, 0.5343, 0.4806, 0.0878]]])


In [27]:
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[0.5531, 0.9460, 0.7111, 0.5016],
         [0.4930, 0.2273, 0.1711, 0.6614],
         [0.2993, 0.3630, 0.1293, 0.3620]],

        [[0.6181, 0.2645, 0.7721, 0.0249],
         [0.6916, 0.8260, 0.2721, 0.1360],
         [0.1296, 0.6350, 0.0410, 0.5590]]])


In [29]:
alike_tensor = torch.rand_like(random_tensor)
print(alike_tensor)

tensor([[[0.8857, 0.4641, 0.1754, 0.8312],
         [0.5424, 0.4473, 0.1672, 0.8553],
         [0.1809, 0.9471, 0.6188, 0.1314]],

        [[0.5200, 0.6144, 0.2606, 0.6996],
         [0.9759, 0.4414, 0.0490, 0.0474],
         [0.8593, 0.2140, 0.0909, 0.4026]]])


In [35]:
a,b,c = alike_tensor.shape
print(a,b,c)

2 3 4


In [36]:
zeros = torch.zeros(size = (3, 4))
new_zeros = torch.zeros_like(zeros)

print(zeros)

print(new_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [38]:
ones = torch.ones(size = (3, 4))
new_ones = torch.ones_like(zeros)

print(ones)

print(new_ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [43]:
var = torch.rand(size = (3, 4), dtype=torch.float16)
var

tensor([[0.8496, 0.4888, 0.5889, 0.3457],
        [0.8276, 0.8481, 0.8306, 0.7969],
        [0.5308, 0.4185, 0.8745, 0.3599]], dtype=torch.float16)

In [45]:
torch.arange(start= 1, end = 20, step = 3)

tensor([ 1,  4,  7, 10, 13, 16, 19])

## Manipulating Tensors

In [3]:
tens = torch.rand(size = (3,4), 
                  dtype= torch.float32,
                  device= torch.device("cuda"),
                  requires_grad= True
                  )

In [32]:
tens2 = torch.rand(size = (3,4), 
                  dtype= torch.float32,
                  device= torch.device("cpu"),
                  requires_grad= True
                  )
tens2

tensor([[0.8046, 0.1031, 0.1014, 0.9716],
        [0.5585, 0.5305, 0.3769, 0.5630],
        [0.5666, 0.0927, 0.0645, 0.2162]], requires_grad=True)

In [9]:
tens2 = tens2.type(torch.float16)

In [14]:
tens * tens # pairwise multiplication

tensor([[0.1653, 0.1965, 0.6277, 0.5939],
        [0.0469, 0.0909, 0.5311, 0.0908],
        [0.0057, 0.0966, 0.2947, 0.0857]], device='cuda:0',
       grad_fn=<MulBackward0>)

In [13]:
tens @ tens.T  # actual matrix multiplication. (3,4) @ (4,3) -> (3,3)

tensor([[1.5834, 1.0313, 0.8242],
        [1.0313, 0.7597, 0.5939],
        [0.8242, 0.5939, 0.4826]], device='cuda:0', grad_fn=<MmBackward0>)

In [15]:
print(tens.device)
print(tens.dtype)
print(tens.shape)
print(tens.ndim)

cuda:0
torch.float32
torch.Size([3, 4])
2


In [16]:
tensor = torch.rand(size = (3,4))
tensor

tensor([[0.1869, 0.8683, 0.4615, 0.9285],
        [0.3724, 0.0210, 0.6983, 0.2200],
        [0.5751, 0.6201, 0.6311, 0.7571]])

In [17]:
tensor + 2

tensor([[2.1869, 2.8683, 2.4615, 2.9285],
        [2.3724, 2.0210, 2.6983, 2.2200],
        [2.5751, 2.6201, 2.6311, 2.7571]])

In [18]:
tensor * 10

tensor([[1.8687, 8.6834, 4.6149, 9.2851],
        [3.7236, 0.2096, 6.9832, 2.2005],
        [5.7508, 6.2007, 6.3106, 7.5713]])

In [19]:
tensor/10

tensor([[0.0187, 0.0868, 0.0461, 0.0929],
        [0.0372, 0.0021, 0.0698, 0.0220],
        [0.0575, 0.0620, 0.0631, 0.0757]])

In [22]:
torch.add(tensor, tensor)

tensor([[0.3737, 1.7367, 0.9230, 1.8570],
        [0.7447, 0.0419, 1.3966, 0.4401],
        [1.1502, 1.2401, 1.2621, 1.5143]])

### Aggregation

In [25]:
tensor

tensor([[0.1869, 0.8683, 0.4615, 0.9285],
        [0.3724, 0.0210, 0.6983, 0.2200],
        [0.5751, 0.6201, 0.6311, 0.7571]])

In [24]:
tensor.min()

tensor(0.0210)

In [29]:
print(torch.min(tensor))
print(torch.min(tensor, dim = 0)) # mins for each column
print(torch.min(tensor, dim = 1)) # mins for each row

tensor(0.0210)
torch.return_types.min(
values=tensor([0.1869, 0.0210, 0.4615, 0.2200]),
indices=tensor([0, 1, 0, 1]))
torch.return_types.min(
values=tensor([0.1869, 0.0210, 0.5751]),
indices=tensor([0, 1, 0]))


In [30]:
print(torch.sum(tensor))
print(torch.sum(tensor, dim = 0)) # mins for each column
print(torch.sum(tensor, dim = 1)) # mins for each row

tensor(6.3402)
tensor([1.1343, 1.5094, 1.7909, 1.9057])
tensor([2.4452, 1.3117, 2.5833])


In [31]:
# Note : mean does not work with torch.long/int64
print(torch.mean(tensor))
print(torch.mean(tensor, dim = 0)) # mins for each column
print(torch.mean(tensor, dim = 1)) # mins for each row

tensor(0.5284)
tensor([0.3781, 0.5031, 0.5970, 0.6352])
tensor([0.6113, 0.3279, 0.6458])


In [44]:
new_ten = torch.arange(0, 20, 2)
new_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
print(new_ten.argmin(), new_ten.min())

tensor(0) tensor(0)


In [46]:
print(new_ten.argmax(), new_ten.max())

tensor(9) tensor(18)


In [37]:
tensor

tensor([[0.1869, 0.8683, 0.4615, 0.9285],
        [0.3724, 0.0210, 0.6983, 0.2200],
        [0.5751, 0.6201, 0.6311, 0.7571]])

In [38]:
tensor.argmin(dim = 0)

tensor([0, 1, 0, 1])

### Advanced Manipulation

* Reshaping - reshapes an input tensor to a given shape
* view - return a view of an input tensor of a given shape but keep the same memory as the original tensor
* stacking - combine multiple tensors (vertical stack or horiz stack)
* Squeeze - removes all `1` dimensions
* Unsqueeze - add...
* permute - return a view of input with dimensions swapped a certain way (einops does it better)

In [50]:
tensor

tensor([[0.1869, 0.8683, 0.4615, 0.9285],
        [0.3724, 0.0210, 0.6983, 0.2200],
        [0.5751, 0.6201, 0.6311, 0.7571]])

In [51]:
new_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
new_ten.reshape(1, 10)

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [53]:
new_ten.reshape(2, 5)

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [55]:
temp = torch.arange(0, 20, 1)
temp

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [57]:
temp.shape

torch.Size([20])

In [58]:
z = temp.view(4, 5)

In [59]:
z

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [61]:
# Now changing z will change x since they share the memory

z[0][0] = -11000

In [62]:
z

tensor([[-11000,      1,      2,      3,      4],
        [     5,      6,      7,      8,      9],
        [    10,     11,     12,     13,     14],
        [    15,     16,     17,     18,     19]])

In [64]:
temp # see 

tensor([-11000,      1,      2,      3,      4,      5,      6,      7,      8,
             9,     10,     11,     12,     13,     14,     15,     16,     17,
            18,     19])

In [65]:
stacked = torch.stack([temp, temp, temp])

print(stacked)
print(stacked.shape)

tensor([[-11000,      1,      2,      3,      4,      5,      6,      7,      8,
              9,     10,     11,     12,     13,     14,     15,     16,     17,
             18,     19],
        [-11000,      1,      2,      3,      4,      5,      6,      7,      8,
              9,     10,     11,     12,     13,     14,     15,     16,     17,
             18,     19],
        [-11000,      1,      2,      3,      4,      5,      6,      7,      8,
              9,     10,     11,     12,     13,     14,     15,     16,     17,
             18,     19]])
torch.Size([3, 20])


In [67]:
stacked = torch.stack([temp, temp, temp], dim = 0)

print(stacked)
print(stacked.shape)

tensor([[-11000,      1,      2,      3,      4,      5,      6,      7,      8,
              9,     10,     11,     12,     13,     14,     15,     16,     17,
             18,     19],
        [-11000,      1,      2,      3,      4,      5,      6,      7,      8,
              9,     10,     11,     12,     13,     14,     15,     16,     17,
             18,     19],
        [-11000,      1,      2,      3,      4,      5,      6,      7,      8,
              9,     10,     11,     12,     13,     14,     15,     16,     17,
             18,     19]])
torch.Size([3, 20])


In [68]:
stacked = torch.stack([temp, temp, temp], dim = 1)

print(stacked)
print(stacked.shape)

tensor([[-11000, -11000, -11000],
        [     1,      1,      1],
        [     2,      2,      2],
        [     3,      3,      3],
        [     4,      4,      4],
        [     5,      5,      5],
        [     6,      6,      6],
        [     7,      7,      7],
        [     8,      8,      8],
        [     9,      9,      9],
        [    10,     10,     10],
        [    11,     11,     11],
        [    12,     12,     12],
        [    13,     13,     13],
        [    14,     14,     14],
        [    15,     15,     15],
        [    16,     16,     16],
        [    17,     17,     17],
        [    18,     18,     18],
        [    19,     19,     19]])
torch.Size([20, 3])


In [71]:
tensor = torch.rand(size = (1,3,4))
print(tensor)
print(tensor.shape)

tensor([[[0.1382, 0.0540, 0.3579, 0.8782],
         [0.1722, 0.3811, 0.4313, 0.4355],
         [0.6782, 0.2927, 0.8337, 0.1278]]])
torch.Size([1, 3, 4])


In [72]:
tensor_squeezed = torch.squeeze(tensor)
print(tensor_squeezed)
print(tensor_squeezed.shape)

tensor([[0.1382, 0.0540, 0.3579, 0.8782],
        [0.1722, 0.3811, 0.4313, 0.4355],
        [0.6782, 0.2927, 0.8337, 0.1278]])
torch.Size([3, 4])


In [77]:
tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim = 1)
print(tensor_unsqueezed)
print(tensor_unsqueezed.shape)

tensor([[[0.1382, 0.0540, 0.3579, 0.8782]],

        [[0.1722, 0.3811, 0.4313, 0.4355]],

        [[0.6782, 0.2927, 0.8337, 0.1278]]])
torch.Size([3, 1, 4])


In [78]:
tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim = 0)
print(tensor_unsqueezed)
print(tensor_unsqueezed.shape)

tensor([[[0.1382, 0.0540, 0.3579, 0.8782],
         [0.1722, 0.3811, 0.4313, 0.4355],
         [0.6782, 0.2927, 0.8337, 0.1278]]])
torch.Size([1, 3, 4])


In [79]:
tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim = 2)
print(tensor_unsqueezed)
print(tensor_unsqueezed.shape)

tensor([[[0.1382],
         [0.0540],
         [0.3579],
         [0.8782]],

        [[0.1722],
         [0.3811],
         [0.4313],
         [0.4355]],

        [[0.6782],
         [0.2927],
         [0.8337],
         [0.1278]]])
torch.Size([3, 4, 1])


### Permute - returns a view of the original tensor, but with dimensions permuted

In [81]:
print(tensor)
print(tensor.shape)

tensor([[[0.1382, 0.0540, 0.3579, 0.8782],
         [0.1722, 0.3811, 0.4313, 0.4355],
         [0.6782, 0.2927, 0.8337, 0.1278]]])
torch.Size([1, 3, 4])


In [82]:
permuted = torch.permute(tensor, dims = (2,0,1))
print(permuted)
print(permuted.shape)

tensor([[[0.1382, 0.1722, 0.6782]],

        [[0.0540, 0.3811, 0.2927]],

        [[0.3579, 0.4313, 0.8337]],

        [[0.8782, 0.4355, 0.1278]]])
torch.Size([4, 1, 3])


### Indexing 

In [83]:
x = torch.randn(size = (2,3,4))
x

tensor([[[ 0.9776, -0.6092,  0.4710, -0.2308],
         [-1.2143, -1.7231,  0.0931, -1.1269],
         [-0.0568,  1.3903,  0.8895, -0.9656]],

        [[-0.7435,  1.6968, -0.2981, -0.7637],
         [ 0.6812,  1.8811,  1.4294,  1.7163],
         [-1.5247,  1.1242,  1.1988, -0.7694]]])

In [84]:
x[0]

tensor([[ 0.9776, -0.6092,  0.4710, -0.2308],
        [-1.2143, -1.7231,  0.0931, -1.1269],
        [-0.0568,  1.3903,  0.8895, -0.9656]])

In [85]:
x[:, 1]

tensor([[-1.2143, -1.7231,  0.0931, -1.1269],
        [ 0.6812,  1.8811,  1.4294,  1.7163]])

In [86]:
x[:, :, 1]

tensor([[-0.6092, -1.7231,  1.3903],
        [ 1.6968,  1.8811,  1.1242]])

In [87]:
x[:, :, 1].shape

torch.Size([2, 3])

## Numpy with Torch

In [88]:
import numpy as np

np_arr = np.arange(1.0, 8.0) # default for np is float64, but for torch is 32.
torch_arr = torch.from_numpy(np_arr)
torch_arr

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [89]:
np_arr = np.arange(1.0, 8.0) # default for np is float64, but for torch is 32.
torch_arr = torch.from_numpy(np_arr).type(torch.float32)
torch_arr

tensor([1., 2., 3., 4., 5., 6., 7.])

In [90]:
np_arr = torch_arr.numpy()
np_arr

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

## Reproducibility

In [91]:
torch.rand(3,3)

tensor([[0.5347, 0.4452, 0.7513],
        [0.8239, 0.1887, 0.3627],
        [0.1705, 0.3438, 0.1283]])

In [97]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # use everytime when creating a random
torch.rand(size = (3,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

## Accessing the GPU

In [99]:
torch.cuda.is_available()

True

In [100]:
tensor = torch.rand(
    size = (3,4),
    device = torch.device("cuda"),
    dtype = torch.float16,
    requires_grad= False
)

In [101]:
tensor

tensor([[0.6128, 0.0101, 0.3984, 0.0403],
        [0.1562, 0.4824, 0.7363, 0.4060],
        [0.5190, 0.2866, 0.2416, 0.9229]], device='cuda:0',
       dtype=torch.float16)

In [102]:
torch.cuda.device_count()

1

In [106]:
# Move a regular tensor to GPU
tensor = torch.rand(
    size = (3,4),
    device = torch.device("cpu"), # no need technically
    dtype = torch.float16,
    requires_grad= False
)

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

tensor = tensor.to(device)

tensor, tensor.device

(tensor([[0.7764, 0.6187, 0.4058, 0.7461],
         [0.5635, 0.7363, 0.8994, 0.3154],
         [0.0098, 0.4102, 0.0811, 0.6333]], device='cuda:0',
        dtype=torch.float16),
 device(type='cuda', index=0))

In [107]:
# How do we move gpu tensors to numpy when needed 

cpu_tens = tensor.cpu()
np_tens = cpu_tens.numpy()
np_tens

array([[0.7764  , 0.6187  , 0.4058  , 0.746   ],
       [0.5635  , 0.7363  , 0.8994  , 0.3154  ],
       [0.009766, 0.4102  , 0.08105 , 0.6333  ]], dtype=float16)